const gulp = require('gulp');
const gulpSass = require('gulp-sass');
const gulpAutoprefixer = require('gulp-autoprefixer');
const gulpClean = require('gulp-clean-css');
const gulpHtml = require('gulp-htmlmin');
const gutil = require( 'gulp-util' );
const ftp = require( 'vinyl-ftp' );

gulp.task('SassToCss', function(){
	return gulp.src('src/sass/*.sass')
	.pipe(gulpSass())
	.pipe(gulpAutoprefixer({
		browsers: 'last 6 versions'
	}))
	.pipe(gulpClean({
		compatibility: 'ie11'
	}))
	.pipe(gulp.dest('build/css'))
})

gulp.task('php', function(){
	return gulp.src('src/*.php')
	.pipe(gulpHtml({
		collapseWhitespace: true,
		includeAutoGeneratedTags: false,
		removeComments: false,
		keepClosingSlash: true,
		preventAttributesEscaping: true,
		removeEmptyAttributes: false,
      	removeRedundantAttributes: false
	}))
	.pipe(gulp.dest('build'))
})

gulp.task('images', function(){
	return gulp.src('src/images/*')
	.pipe(gulp.dest('build/images'))
})

gulp.task('fonts', function(){
	return gulp.src('src/fonts/*')
	.pipe(gulp.dest('build/fonts'))
})

var user = ''; 
var password = '';
var host = '';  
var port = 21;  
var localFilesGlob = ['./build/**/*'];
var remoteFolder = '/web/wp-content/themes/'
function getFtpConnection() {  
    return ftp.create({
        host: host,
        port: port,
        user: user,
        password: password,
        parallel: 10,
        log: gutil.log
    });
}

gulp.task('ftp-deploy-watch', function() {
    var conn = getFtpConnection();
    gulp.watch(localFilesGlob)
    .on('change', function(event) {
      console.log('Changes detected! Uploading file "' + event.path + '", ' + event.type);
      return gulp.src( [event.path], { base: '.', buffer: false } )
        .pipe( conn.newer( remoteFolder ) ) // only upload newer files 
        .pipe( conn.dest( remoteFolder ) )
      ;
    });
});

gulp.task('watch', function(){
	gulp.watch('src/sass/*.sass', ['SassToCss'])
	gulp.watch('src/*.php', ['php'])
	gulp.watch('src/images/*', ['images'])
	gulp.watch('src/fonts/*', ['fonts'])
})
